server {
  listen 80;
  server_name another.com;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name another.com;

  ssl_certificate     certs/another.com.crt;
  ssl_certificate_key certs/another.com.key;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
  add_header X-Robots-Tag "noindex" always;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://127.0.0.1:8081;
  }
}
